### ISSUE TITLE
GUI?

### ISSUE THREAD

**Issue by snaildos** [heXeo/ubnt-fan-speed#2]
GUI support maybe?
and a easy setup? like apt install?
I don't know. I don't want to build it myself.

**Comment by nekuz0r** [comment]
@snaildos No need to build it yourself.
A prebuilt binary is provided here : https://github.com/heXeo/ubnt-fan-speed/releases

**Comment by nekuz0r** [comment]
This is a drop-in replacement for the original binary.
If you think some improvement can be done in regard of the installation process, feel free to contribute and open a PR :wink:

**Comment by snaildos** [comment]
Alright, I'm scared about these settings, Is there some information I should know off? Is there any GUI config generator?

**Comment by nekuz0r** [comment]
@snaildos No, there is no GUI config generator.
Frankly, i don't see anything you could mess up if you follow the instructions in the [readme](https://github.com/heXeo/ubnt-fan-speed#installation---udmudmpro).
Please make a backup of your configuration first, that way if anything goes wrong you will be able to restore from it.

You can use the configuration file provided in the readme as a starting point, it will mimic the behavior of the stock binary.

**Comment by snaildos** [comment]
What is the default configuration set on? Is it what ubuiqti devices are normally set on? Or is it more cooled?

**Comment by nekuz0r** [comment]
@snaildos It's configured the same as what the device normally do.
If you want to force the fan to spin at a minimum level you have to change `minimum_fan_speed` to a value between 0 and 255 (0 is what the device normally do) and enable `force_minimum_fan_speed` by setting it to 1.

So if you want the fan the spin at a minimum of 50% of it's maximum RPM all the time in order to make it more cooled, you can use the following settings
```
minimum_fan_speed=127
force_minimum_fan_speed=1
```
NOTE: this is the default device behaviour if a HDD/SSD is present in the drive bay.

`minimum_fan_speed` is only effective if `force_minimum_fan_speed` is enabled.
